### ISSUE TITLE
No shadow

### ISSUE THREAD

**Issue by Asthestarsfalll** [tonyfettes/fcitx5-nord#4]
There is no shadow like the picture you give 
![Uploading image.png…]()

**Comment by Asthestarsfalll** [comment]
![image](https://user-images.githubusercontent.com/72954905/126951003-dae765f7-216b-4fa4-b0ae-6ec3ed65f17d.png)

**Comment by tonyfettes** [comment]
Shadow is cool, but this theme does not comes with shadow. I will take new screenshots without shadows and replace current ones. Sorry for my mistakes and thank you for your reminder.

Maybe I will add a variant with shadow in the furture...
